# Generated by Django 4.2.1 on 2023-05-15 19:23

import applications.feedback.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_alter_episodes_episode_alter_series_preview_and_more'),
        ('feedback', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='series',
            field=models.ForeignKey(default=applications.feedback.models.get_default_series, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='series.series'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='series',
            field=models.ForeignKey(default=applications.feedback.models.get_default_series, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='series.series'),
        ),
        migrations.AddField(
            model_name='like',
            name='series',
            field=models.ForeignKey(default=applications.feedback.models.get_default_series, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='series.series'),
        ),
        migrations.AddField(
            model_name='rating',
            name='series',
            field=models.ForeignKey(default=applications.feedback.models.get_default_series, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='series.series'),
        ),
    ]
