# Generated by Django 4.2.1 on 2023-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=180)),
                ('episode', models.FileField(upload_to='series/series-episode/')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('episodes', models.ManyToManyField(to='series.episodes', verbose_name='серии')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trailer', models.FileField(upload_to='series/series-trailer/')),
            ],
            options={
                'verbose_name': 'Трейлер',
                'verbose_name_plural': 'Трейлеры',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершен', 'Завершен'), ('Заброшен', 'Заброшен'), ('Анонсировано', 'Анонсировано')], max_length=100)),
                ('preview', models.ImageField(upload_to='series/series-preview/')),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='series.genre', verbose_name='жанры')),
                ('season', models.ManyToManyField(blank=True, to='series.season', verbose_name='сезоны')),
                ('trailer', models.ManyToManyField(blank=True, to='series.trailer', verbose_name='трейлеры')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
    ]
