# Generated by Django 4.2.1 on 2023-05-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=180)),
                ('episode', models.FileField(upload_to='series/series-episode/')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('episodes', models.ManyToManyField(blank=True, related_name='episodes', to='series.episodes')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trailer', models.FileField(upload_to='series/series-trailer/')),
            ],
            options={
                'verbose_name': 'Трейлер',
                'verbose_name_plural': 'Трейлеры',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершен', 'Завершен'), ('Заброшен', 'Заброшен'), ('Анонсировано', 'Анонсировано')], max_length=100)),
                ('preview', models.ImageField(upload_to='series/series-preview/')),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='genres', to='series.genre')),
                ('season', models.ManyToManyField(blank=True, related_name='seasons', to='series.season')),
                ('trailer', models.ManyToManyField(blank=True, related_name='trailers', to='series.trailer')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_season', to='series.series'),
        ),
    ]
