# Generated by Django 4.2.1 on 2023-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trailer', models.FileField(upload_to='series-trailer/')),
            ],
            options={
                'verbose_name': 'Трейлер',
                'verbose_name_plural': 'Трейлеры',
            },
        ),
        migrations.AlterModelOptions(
            name='episodes',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.RenameField(
            model_name='series',
            old_name='created_at',
            new_name='upload_at',
        ),
        migrations.RemoveField(
            model_name='episodes',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='series',
        ),
        migrations.AddField(
            model_name='episodes',
            name='description',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodes',
            name='episode',
            field=models.FileField(default=1, upload_to='series-episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершен', 'Завершен'), ('Заброшен', 'Заброшен'), ('Анонсировано', 'Анонсировано')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('episodes', models.ManyToManyField(to='series.episodes', verbose_name='серии')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='season',
            field=models.ManyToManyField(to='series.season', verbose_name='сезоны'),
        ),
    ]
