# Generated by Django 4.2.1 on 2023-05-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='episodes',
            field=models.ManyToManyField(blank=True, related_name='season_episodes', to='series.episodes'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='season_series', to='series.series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(related_name='series_genres', to='series.genre'),
        ),
    ]
