# Generated by Django 4.2.1 on 2023-05-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_season_episodes_alter_season_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='release_year',
            field=models.PositiveIntegerField(default='2017'),
        ),
    ]
