# Generated by Django 4.2.1 on 2023-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_trailer_alter_episodes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='series',
            name='trailer',
            field=models.ManyToManyField(to='series.trailer', verbose_name='трейлеры'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
