# Generated by Django 4.2.1 on 2023-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_season_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='release_year',
            new_name='release',
        ),
    ]
