# Generated by Django 4.2.1 on 2023-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('adventure', 'adventure'), ('horror', 'horror'), ('fantastic', 'fantastic'), ('romance', 'romance'), ('drama', 'drama'), ('action', 'action')], max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='films_avatar/')),
                ('film', models.FileField(upload_to='films_film/')),
                ('director', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
