# Generated by Django 4.2.1 on 2023-05-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанp',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Филм', 'verbose_name_plural': 'Филмы'},
        ),
        migrations.RemoveField(
            model_name='films',
            name='genre',
        ),
        migrations.AddField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(to='films.genre', verbose_name='жанры'),
        ),
    ]
