# Generated by Django 4.2.1 on 2023-05-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_films_trailer'),
        ('films', '0002_genre_alter_films_options_remove_films_genre_and_more'),
    ]

    operations = [
    ]
