# Generated by Django 4.2.1 on 2023-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_merge_20230512_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='avatar',
            field=models.ImageField(default=1, upload_to='films_avatar/'),
            preserve_default=False,
        ),
    ]
