# Generated by Django 4.2.1 on 2023-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_films_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterField(
            model_name='films',
            name='avatar',
            field=models.ImageField(upload_to='film/films_avatar/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='film',
            field=models.FileField(upload_to='film/films_film/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='trailer',
            field=models.FileField(upload_to='film/film_trailer'),
        ),
    ]
